### ISSUE TITLE
siege work error

### ISSUE THREAD

**Issue by lrz2010** [Jonathan57500/aion-lightning-2.7#24] opened 2019-01-02 14:43 UTC
When I open any event ，Seige There's appear two bosses and double the monster.
This error only occurs in the I open event Service

**Comment by Jonathan57500** [comment] 2019-01-05 19:14
I've tested with both fortress in Inggison, no problem has occured.
Please make a fresh install of this server, then give me steps to reproduce this error.
Give more details, like what fortress ID, what faction during the siege, if there is a legion owner, etc.

**Comment by lrz2010** [comment] 2019-01-06 08:31
frist,open event.
edit \AL-Game\config\main\events.properties
# Enable Event Service (under development)
gameserver.event.service.enable = true
edit \AL-Game\data\static_data\events_config\event_config.xml
any event start sach as <event name="Ascension Energy" start="2019-01-01T00:00:00+00:00" end="2019-10-26T00:00:00+00:00">
then start server
open Client
//siege start 1011
![qq 20190104030521](https://user-images.githubusercontent.com/44985031/50733862-64970780-11d0-11e9-9532-167753c2fa7e.png)
If you don't understand，Please watch this video. 
Thanks you very much
[https://youtu.be/W4J1wfYYpI4](url)

**Comment by Jonathan57500** [comment] 2019-05-23 12:50
As explained in the configuration file, this is a functionality under development. That means that 8 years ago, when Lignthing worked on this emu the functionality was not officially supported by the emulator as still in development. This has been enhanced in next releases (like 3.X) of Lightning.
Since we are working on this emulator, we add and modify a lot of existing methods without taking any consideration of events functionality because it didn't work correctly when it was Lightning released. So we did not give any importance to its compatibility with our major updates.
In my point of view this is not a very urgent need for this emulator, we still have some issues on skills, quests, pets, summons, geodata and so much more, so I think priority should be given to these points before we make "events" to work correctly.

The error you have when entering the world looks to be related to quest list of your player, I think that there are additional quests related to events you enabled that are not correctly scripted, and note that when you have this error message some other functionalities should not work correctly for this player (like inventory, skills, quests, etc.).

I'm closing this bug as this is more an incoming enhancement to make events working properly, I'm adding a note in the TODO list of this project Wiki, when a developer will have time he will take a look on it :)
Anyway thanks to you for participating.

**Closed by Jonathan57500** 2019-05-23 12:50 UTC
Labels: Wait for action
